apiVersion : apps/v1
kind: Deployment
metadata:
  name: testrepodevimage 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testrepodevimage
  template:
    metadata:
      labels:
        app: testrepodevimage 
    spec:
      containers:
        - name: testrepodevimage 
          image: primaryregistry01.azurecr.io/testrepodevimage
          ports:
          - containerPort: 80